# Generated by Django 5.0.1 on 2025-10-22 08:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal')], help_text='Type of payment gateway', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gateway is currently active')),
                ('is_sandbox', models.BooleanField(default=True, help_text='Whether this gateway is in sandbox/test mode')),
                ('api_key', models.TextField(help_text='Encrypted API key for the gateway')),
                ('api_secret', models.TextField(help_text='Encrypted API secret for the gateway')),
                ('webhook_secret', models.TextField(blank=True, help_text='Encrypted webhook secret for the gateway')),
                ('supported_currencies', models.JSONField(default=list, help_text='List of supported currency codes')),
                ('configuration', models.JSONField(default=dict, help_text='Additional gateway-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('wallet', 'Digital Wallet'), ('upi', 'UPI'), ('net_banking', 'Net Banking')], max_length=20)),
                ('card_last_four', models.CharField(blank=True, help_text='Last four digits of card (for display)', max_length=4)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=20)),
                ('card_exp_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('card_exp_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2050)])),
                ('gateway_method_id', models.CharField(help_text='Payment method ID from the gateway', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='payments.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'gateway_method_id')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('ride_payment', 'Ride Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='ride_payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=255)),
                ('gateway_payment_intent_id', models.CharField(blank=True, help_text='Payment intent ID from the gateway', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payment was processed', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional payment metadata')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentgateway')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('ride_cancelled', 'Ride Cancelled'), ('service_issue', 'Service Issue'), ('customer_request', 'Customer Request'), ('system_error', 'System Error'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_refund_id', models.CharField(blank=True, help_text='Refund ID from the payment gateway', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the refund')),
                ('metadata', models.JSONField(default=dict, help_text='Additional refund metadata')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_processed', 'Payment Processed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('refund_initiated', 'Refund Initiated'), ('refund_processed', 'Refund Processed'), ('webhook_received', 'Webhook Received'), ('error_occurred', 'Error Occurred')], max_length=30)),
                ('description', models.TextField(help_text='Description of the action')),
                ('request_data', models.TextField(blank=True, help_text='Encrypted request data')),
                ('response_data', models.TextField(blank=True, help_text='Encrypted response data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_7b4bf7_idx'), models.Index(fields=['action', '-created_at'], name='payments_pa_action_795962_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx'),
        ),
    ]
