# Generated by Django 5.0.1 on 2025-10-22 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Algorithm name', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this algorithm is active')),
                ('priority', models.IntegerField(default=0, help_text='Algorithm priority (higher = preferred)')),
                ('max_search_radius_km', models.FloatField(default=10.0, help_text='Maximum search radius in kilometers')),
                ('max_vehicles_to_consider', models.IntegerField(default=20, help_text='Maximum number of vehicles to consider')),
                ('min_battery_level', models.IntegerField(default=20, help_text='Minimum battery level for vehicle selection')),
                ('distance_weight', models.FloatField(default=0.4, help_text='Weight for distance factor in scoring')),
                ('battery_weight', models.FloatField(default=0.2, help_text='Weight for battery level in scoring')),
                ('efficiency_weight', models.FloatField(default=0.2, help_text='Weight for vehicle efficiency in scoring')),
                ('availability_weight', models.FloatField(default=0.2, help_text='Weight for availability time in scoring')),
                ('max_processing_time_seconds', models.IntegerField(default=30, help_text='Maximum time allowed for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Algorithm Config',
                'verbose_name_plural': 'Dispatch Algorithm Configs',
                'db_table': 'dispatch_algorithconfig',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for these metrics')),
                ('algorithm_name', models.CharField(help_text='Algorithm name', max_length=50)),
                ('total_requests', models.IntegerField(default=0, help_text='Total dispatch requests')),
                ('successful_assignments', models.IntegerField(default=0, help_text='Successful vehicle assignments')),
                ('failed_assignments', models.IntegerField(default=0, help_text='Failed assignments')),
                ('expired_requests', models.IntegerField(default=0, help_text='Expired requests')),
                ('average_processing_time_seconds', models.FloatField(blank=True, help_text='Average processing time in seconds', null=True)),
                ('average_distance_km', models.FloatField(blank=True, help_text='Average distance to assigned vehicle', null=True)),
                ('average_eta_minutes', models.IntegerField(blank=True, help_text='Average ETA in minutes', null=True)),
                ('success_rate', models.FloatField(blank=True, help_text='Success rate percentage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Metrics',
                'verbose_name_plural': 'Dispatch Metrics',
                'db_table': 'dispatch_metrics',
                'ordering': ['-date', 'algorithm_name'],
                'indexes': [models.Index(fields=['date', 'algorithm_name'], name='dispatch_me_date_851ed3_idx'), models.Index(fields=['-date'], name='dispatch_me_date_fcb001_idx')],
                'unique_together': {('date', 'algorithm_name')},
            },
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('assigned', 'Assigned'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', help_text='Current dispatch status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Dispatch priority level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this dispatch request expires')),
                ('algorithm_used', models.CharField(blank=True, help_text='Algorithm used for vehicle assignment', max_length=50)),
                ('search_radius_km', models.FloatField(blank=True, help_text='Search radius used for finding vehicles', null=True)),
                ('vehicles_considered', models.IntegerField(default=0, help_text='Number of vehicles considered for assignment')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for dispatch failure', max_length=100)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('assigned_vehicle', models.ForeignKey(blank=True, help_text='Vehicle assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_assignments', to='fleet.vehicle')),
                ('ride', models.OneToOneField(help_text='Ride requesting dispatch', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_request', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Dispatch Request',
                'verbose_name_plural': 'Dispatch Requests',
                'db_table': 'dispatch_dispatchrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dispatch_di_status_8ab010_idx'), models.Index(fields=['priority', '-created_at'], name='dispatch_di_priorit_c147f5_idx'), models.Index(fields=['expires_at'], name='dispatch_di_expires_4ab1ee_idx')],
            },
        ),
    ]
