# Generated by Django 5.0.1 on 2025-10-22 06:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Tesla Model 3)', max_length=100)),
                ('manufacturer', models.CharField(default='Tesla', help_text='Vehicle manufacturer', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('compact', 'Compact'), ('luxury', 'Luxury')], default='sedan', help_text='Type of vehicle', max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('assigned', 'Assigned'), ('in_ride', 'In Ride'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='offline', help_text='Current vehicle status', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, help_text='Current latitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('current_longitude', models.FloatField(blank=True, help_text='Current longitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('battery_level', models.IntegerField(default=100, help_text='Current battery level percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mileage', models.FloatField(default=0.0, help_text='Total mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('passenger_capacity', models.PositiveIntegerField(default=4, help_text='Maximum passenger capacity', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('has_wheelchair_access', models.BooleanField(default=False, help_text='Vehicle has wheelchair accessibility')),
                ('has_child_seat', models.BooleanField(default=False, help_text='Vehicle has child seat available')),
                ('last_maintenance', models.DateTimeField(blank=True, help_text='Date of last maintenance', null=True)),
                ('next_maintenance_due', models.DateTimeField(blank=True, help_text='Date when next maintenance is due', null=True)),
                ('maintenance_mileage_threshold', models.FloatField(default=10000.0, help_text='Mileage threshold for maintenance (km)')),
                ('total_rides', models.PositiveIntegerField(default=0, help_text='Total number of rides completed')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue generated', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time vehicle sent telemetry data', null=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'fleet_vehicle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='fleet_vehic_status_f5cfd7_idx'), models.Index(fields=['license_plate'], name='fleet_vehic_license_8e5cca_idx'), models.Index(fields=['current_latitude', 'current_longitude'], name='fleet_vehic_current_a09688_idx'), models.Index(fields=['battery_level'], name='fleet_vehic_battery_db6e12_idx'), models.Index(fields=['last_seen'], name='fleet_vehic_last_se_4e6845_idx'), models.Index(fields=['next_maintenance_due'], name='fleet_vehic_next_ma_472c34_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('upgrade', 'Upgrade'), ('emergency', 'Emergency Repair')], help_text='Type of maintenance', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Maintenance status', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='Scheduled maintenance date')),
                ('started_at', models.DateTimeField(blank=True, help_text='When maintenance actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When maintenance was completed', null=True)),
                ('description', models.TextField(help_text='Description of maintenance work')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from technician')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated maintenance cost', max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual maintenance cost', max_digits=10, null=True)),
                ('mileage_at_maintenance', models.FloatField(blank=True, help_text='Vehicle mileage at time of maintenance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(blank=True, help_text='Technician assigned to this maintenance', limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle being maintained', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'fleet_maintenancerecord',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['vehicle', '-scheduled_date'], name='fleet_maint_vehicle_a16506_idx'), models.Index(fields=['status'], name='fleet_maint_status_bbe1cd_idx'), models.Index(fields=['maintenance_type'], name='fleet_maint_mainten_c9e50d_idx'), models.Index(fields=['scheduled_date'], name='fleet_maint_schedul_8d88d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('speed', models.FloatField(help_text='Current speed in km/h', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('heading', models.FloatField(help_text='Direction heading in degrees', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('battery_level', models.IntegerField(help_text='Battery level percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.FloatField(blank=True, help_text='Internal temperature in Celsius', null=True)),
                ('engine_status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('charging', 'Charging'), ('error', 'Error')], default='idle', help_text='Engine/motor status', max_length=20)),
                ('diagnostic_codes', models.JSONField(blank=True, default=list, help_text='Diagnostic trouble codes')),
                ('passenger_count', models.PositiveIntegerField(default=0, help_text='Current number of passengers', validators=[django.core.validators.MaxValueValidator(8)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this telemetry data was recorded')),
                ('vehicle', models.ForeignKey(help_text='Vehicle this telemetry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Telemetry',
                'verbose_name_plural': 'Vehicle Telemetry Data',
                'db_table': 'fleet_vehicletelemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='fleet_vehic_vehicle_d360a2_idx'), models.Index(fields=['latitude', 'longitude'], name='fleet_vehic_latitud_c5c74b_idx'), models.Index(fields=['timestamp'], name='fleet_vehic_timesta_72da55_idx'), models.Index(fields=['battery_level'], name='fleet_vehic_battery_14cd75_idx'), models.Index(fields=['speed'], name='fleet_vehic_speed_c25430_idx')],
            },
        ),
    ]
