# Generated by Django 5.0.1 on 2025-10-22 07:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('north_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('south_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('east_lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('west_lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Current surge pricing multiplier', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'db_table': 'rides_servicearea',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latitude', models.FloatField(help_text='Pickup location latitude', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('pickup_longitude', models.FloatField(help_text='Pickup location longitude', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('pickup_address', models.CharField(blank=True, help_text='Pickup address description', max_length=500)),
                ('destination_latitude', models.FloatField(help_text='Destination latitude', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('destination_longitude', models.FloatField(help_text='Destination longitude', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('destination_address', models.CharField(blank=True, help_text='Destination address description', max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('pickup', 'En Route to Pickup'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', help_text='Current ride status', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_started_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fare_estimate', models.DecimalField(decimal_places=2, help_text='Estimated fare before ride', max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Final fare after ride completion', max_digits=10, null=True)),
                ('estimated_distance_km', models.FloatField(blank=True, help_text='Estimated distance in kilometers', null=True)),
                ('actual_distance_km', models.FloatField(blank=True, help_text='Actual distance traveled in kilometers', null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('user_cancelled', 'User Cancelled'), ('driver_cancelled', 'Driver Cancelled'), ('no_driver', 'No Driver Available'), ('system_error', 'System Error'), ('payment_failed', 'Payment Failed')], help_text='Reason for cancellation', max_length=20, null=True)),
                ('cancellation_notes', models.TextField(blank=True, help_text='Additional cancellation notes')),
                ('passenger_count', models.PositiveIntegerField(default=1, help_text='Number of passengers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('requires_wheelchair_access', models.BooleanField(default=False, help_text='Requires wheelchair accessible vehicle')),
                ('requires_child_seat', models.BooleanField(default=False, help_text='Requires child seat')),
                ('pickup_notes', models.TextField(blank=True, help_text='Special pickup instructions')),
                ('ride_notes', models.TextField(blank=True, help_text='Special ride instructions')),
                ('rider_rating', models.IntegerField(blank=True, help_text='Rider rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rider_feedback', models.TextField(blank=True, help_text='Rider feedback')),
                ('rider', models.ForeignKey(help_text='User who booked the ride', on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Assigned vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'db_table': 'rides_ride',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('pickup_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('destination_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('destination_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('requires_wheelchair_access', models.BooleanField(default=False)),
                ('requires_child_seat', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('matched_ride', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='rides.ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Request',
                'verbose_name_plural': 'Ride Requests',
                'db_table': 'rides_riderequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', '-requested_at'], name='rides_ride_rider_i_0012ba_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['vehicle', '-requested_at'], name='rides_ride_vehicle_01e70c_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', '-requested_at'], name='rides_ride_status_4f9460_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='rides_ride_pickup__b78bad_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['destination_latitude', 'destination_longitude'], name='rides_ride_destina_685c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['requested_at'], name='rides_ride_request_c8cf74_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['status', '-created_at'], name='rides_rider_status_057c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['expires_at'], name='rides_rider_expires_17a1fa_idx'),
        ),
    ]
